### ISSUE TITLE
Relative links are broken if current location is not not ending in `/`

### ISSUE THREAD

**Issue by WolverinDEV** [Valthrun/Wiki#21]

**Comment by imwqqz** [comment]
No issue where found here, can u re-create it?

**Comment by WolverinDEV** [comment]
Go to https://wiki.valth.run/getting-started/driver/ and click on a driver -> success
Go to https://wiki.valth.run/getting-started/driver and click on a driver -> broken link

**Comment by imwqqz** [comment]
Welp my browsers auto add the final `/` lol

**Comment by imwqqz** [comment]
After a test every browser include Firefox, Microsoft Edge, Chrome will add `/` to final url. and i cannot re-create the err

**Comment by WolverinDEV** [comment]
fixed :)
